### ISSUE TITLE
[개선 사항] 체크박스 유지

### ISSUE THREAD

**Issue by JeongbinYoon** [JangHyunjeong/kws-react-todo#1]
완료항목 체크 후 필터 진행중으로 변경 -> 이후 필터 전체로 변경 시 완료된 항목 체크 풀려서 유지되면 좋을 것 같습니다
버튼에 커서 반응도 있으면 좋을 것 같아요!

<img width="500" alt="스크린샷 2024-11-12 오후 8 58 16" src="https://github.com/user-attachments/assets/7e7c467a-ead3-41d6-b0cb-b6cb06b6cb10">

**Comment by JangHyunjeong** [comment]
이부분 발견하지 못했었네요! 
감사합니다~ 해당사항 수정하여 적용해두었습니다! (❁´◡`❁)
